### ISSUE TITLE
Conductor connect to ElasticSearch failed: NoNodeAvailableException

### ISSUE THREAD

**Issue by leikao** [leikao/conductor#1]
Conductor connect to Huawei Cloud's ElasticSearch Transport (9300) failed:
```
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{m1YURNHMTKuoleRuLnBexQ}{es.domain.com}{xxx.xxxx.xxx.xxx:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:366)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:730)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
	at com.netflix.conductor.dao.es5.index.ElasticSearchDAOV5.setup(ElasticSearchDAOV5.java:152)
	at com.netflix.conductor.bootstrap.Main.main(Main.java:71)
```

ElasticSearch's 9300 port is listening and can established from conductor's host.

**Comment by leikao** [comment]
You should set the value of `client.transport.sniff` to `false` when using Java clients to communicate with Huawei Cloud's ElasticSearch.

Huawei Cloud's ElasticSearch is listening on private IP address which you could not communicate with it directly, the IP addresses you got from the Console is not real IP used by backend services.
Conductor is unable to communicate with the auto-discoveried private IP addresses when the `sniff` toggle is on.
